<template>
<div class="reminder slide-in-blurred-top">
  <span>You can open this gallery page any time from <br>the browser context menu (right-click) </span>
  <div >
    <img :src="img" alt="">
  </div>
  <fa-solid-times class="hide" @click="hide" />
</div>
</template>

<script>
import contextMenuImage from './contextMenuReminder.png';

export default {
  name: "contextMenuReminder",
  data() {
    return {
      img: contextMenuImage,
    }
  },
  methods: {
    hide: function() {
      this.$store.commit('stickyProp', { key: 'contextMenuReminder', value: false });
    }, 
  }
  
};
</script>
 
<style scoped lang='scss'>


img, span { display: inline-block; }

img { max-width: 100%; }
span { padding-bottom: 10px; }

.reminder {
  position: relative;
  text-align: center;
  margin: -40px auto 20px;
  max-width: 380px;
  border-radius: 12px;
  padding: 10px 20px;
  @include themify($themes) {
    border: 2px solid themed(audibleOrange);
    background: lighten( themed(backColor), 9);
    color: themed(frontColor);
  }
}

a {
  @include themify($themes) {
    color: themed(frontColor) !important;
    text-decoration: underline !important;
  }
}

.hide {
  cursor: pointer;
  @extend .center-contents;
  width: 15px;
  height: 15px;
  padding: 4px;
  border-radius: 999999px;
  @include themify($themes) {
    border: 2px solid themed(audibleOrange);
    background: lighten( themed(backColor), 9);
    color: themed(frontColor);
  }
  position: absolute;
  top: -8px;
  right: -8px;
  box-shadow: 0 2px 15px rgba(#000, .2);
}


/* ----------------------------------------------
 * Generated by Animista on 2021-11-7 6:2:53
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes slide-in-blurred-top{0%{-webkit-transform:translateY(-1000px) scaleY(2.5) scaleX(.2);transform:translateY(-1000px) scaleY(2.5) scaleX(.2);-webkit-transform-origin:50% 0;transform-origin:50% 0;-webkit-filter:blur(40px);filter:blur(40px);opacity:0}100%{-webkit-transform:translateY(0) scaleY(1) scaleX(1);transform:translateY(0) scaleY(1) scaleX(1);-webkit-transform-origin:50% 50%;transform-origin:50% 50%;-webkit-filter:blur(0);filter:blur(0);opacity:1}}@keyframes slide-in-blurred-top{0%{-webkit-transform:translateY(-1000px) scaleY(2.5) scaleX(.2);transform:translateY(-1000px) scaleY(2.5) scaleX(.2);-webkit-transform-origin:50% 0;transform-origin:50% 0;-webkit-filter:blur(40px);filter:blur(40px);opacity:0}100%{-webkit-transform:translateY(0) scaleY(1) scaleX(1);transform:translateY(0) scaleY(1) scaleX(1);-webkit-transform-origin:50% 50%;transform-origin:50% 50%;-webkit-filter:blur(0);filter:blur(0);opacity:1}}
.slide-in-blurred-top{-webkit-animation:slide-in-blurred-top .6s cubic-bezier(.23,1.000,.32,1.000) .1s both;animation:slide-in-blurred-top .6s cubic-bezier(.23,1.000,.32,1.000) .1s both}

</style>