
export default {
  // States that persist by reading and writing to localStorage
  sticky: {
    lightSwitch: 1,
    lightSwitchSetByUser: false,
    // sortValues: false,
    viewMode: 'grid',
    gridMaxWidth: null,
    coverSize: null,
    globalSettingsMobileHeight: null,
    gridDetailsMode: 'off',
    gridListCols: null,
    listColumnsHidden: null,
    listColumnsOrder: null,
    listColumnsFrozen: null,
    listColumnsWidths: null,
    booksInSeriesToggle: false,
    collectionsDrawerToggle: true,
    exportSettingsGallery: null,
    exportSettingsCSVdataSources: null,
    exportSettingsCSVcompatibility: null,
    exportSettingsGoodreadsIdentifier: null,
    booksInSeriesAll: true,
    booksInSeriesFinished: true,
    booksInSeriesLinkMode: 'app',
    booksInSeriesCoverGrid: false,
    booksInSeriesHideUnavailable: false,
    subPageSource: 'library',
    bookDetailsCollapsedCover: false,
    bookDetailsCollapsedDetails: false,
    contextMenuReminder: true,
    detailLinksExternal: false,
    disableSearchAutocomplete: false,
    bookDetailSettings: {
      minHeight: null,
      titleLong: false,
      sidebar: {
        show: true,
        iconToolbar: true,
        seriesList: true,
        collectionsList: true,
      },
      carousel: true,
      playButton: true,
      cloudPlayer: false,
      appLink: false,
      statusIndicators: true,
      whispersync: true,
      plusCatalog: true,
      favorite: true,
      finished: true,
      reverseDirection: false,
      hideFirstSection: true,
    },
    collectionsHidePremade: false,
    player: {
      books: [
        // { asin: x, progress: 0 },
      ],
    },
    seriesFilters: {
      inLibrary: null,
      notInLibrary: null,
    },
    useHaptics: false,
    githubSelectedRepo: '',
  },
  // States that don't persist
  globalSettingsOpen: false,
  globalSettingsDrawerHidden: false,
  searchMounted: false,
  searchCollection: [],
  mutatingCollection: [],
  collectionSource: null,
  pageCollection: null,
  route: null,
  routeParams: null,
  audibledata: null,
  urlOrigin: null,
  searchQuery: "",
  standalone: null,
  displayMode: null,
  listRenderingOpts: null,
  windowWidth: window.innerWidth,
  showBackground: false,
  refreshViewTimeStamp: new Date().getTime(),
  showRoute: true,
  pageTitle: null,
  pageSubTitle: null,
  version: import.meta.env.PACKAGE_VERSION,
  extractSettings: null,
  siteOnline: true,
  searchOptCloseGuard: false,
  bundlingGallery: false,
  bookDetails: {
    book: null,
    index: -1,
  },
  // Open book-details panel coordination for the virtualized views:
  // index = the open book's index in getters.collection, gapHeight = the panel's
  // measured height so the virtualizer can reserve space for it at that row.
  openDetails: {
    index: -1,
    gapHeight: 0,
  },
  // Grid columns measured by the grid view, shared so book-details vertical arrow
  // nav steps by the correct number of covers per row.
  gridCols: 1,
  gridCoverWidth: 182,
  gridDefaultMaxWidth: 728,
  gridAvailableWidth: 728,
  coverSizeMin: 80,
  coverSizeMinMobile: 50,
  coverSizeMax: 500,
  searchOptOpenHeight: null,
  devMode: import.meta.env.MODE === 'development',
  lazyScroll: true,
  navHistory: {
    btnNavigation: false,
    forward: [],
    back: [],
  },
  modal: {
    saveLocally: false,
  },
  preventScrolling: false,
  playingAudio: false,
  topNavOffset: 0,
  bookClicked: false,
  audioPlayer: {
    audio: null, // input object
    // howler: null,
    timeDisplay: '00:00',
    timeDisplayLeft: '00:00',
    progress: 0,
    sample: true,
    playing: false,
  },
  showMobilePlayer: false,
  desktopPlayerHeight: null,
  mobileWidth: 630,
  // Last visible item index written by the active virtualizer, used by the segment
  // rail label. -1 means not yet measured (label stays hidden until set).
  scrollVisibleIndex: -1,
};
