<template>

  <!-- 
    This v-show on the parent and v-if on the child element is to retain 
    inline styles when the user opens and closes the sample audio player 
  -->
  <div id="mobile-menu-floaters" :class="{ mobile: mobileMenuOpen }">
    <div class="second-row">
      
      <div v-if="$store.state.searchMounted && !mobileMenuOpen" class="search-btn" @click="$emit('startSearching')"
        :style="{ top: showMobilePlayerButton ? '-93px' : '-46px' }"
      >
        <fa-solid-search/>
      </div>
      
      <div v-if="showMobilePlayerButton" class="mobile-player-button" @click="$store.commit('prop', { key: 'showMobilePlayer', value: true });">
        <!-- <material-symbols-play-circle/> -->
        <!-- <ic-twotone-play-circle-filled-white/> -->
        <ph-play-fill/>
        <!-- <fa6-solid-headphones-simple/> -->
        <!-- <streamline-interface-id-voice-1-identification-secure-id-soundwave-sound-voice-security/> -->
        <!-- <streamline-interface-id-voice-scan-identification-secure-id-soundwave-sound-voice-brackets-security/> -->
        <!-- <solar-soundwave-bold/> -->
        <!-- <material-symbols-video-audio-call/> -->
      </div>
      
      <gallery-back-forward-btns v-if="$store.state.displayMode && !mobileMenuOpen" />
      
      <div class="burger-menu" @click="$emit('update:mobileMenuOpen', !mobileMenuOpen)">
        <fa-solid-bars class="brgr-btn" />
        <!-- <div class="player-open-indicator" v-if="$store.state.playingAudio">
          <fa-solid-music class="brgr-btn" />
        </div> -->
      </div>
      
    </div>
  </div>
  
</template>

<script>
export default {
  name: "mobileMenuFloaters",
  props: ['mobileMenuOpen', 'mobileThreshold'],
  data: function() {
    return {
      store: this.$store.state,
    };
  },
  
  computed: {
    showMobilePlayerButton() {
      return !this.mobileMenuOpen && this.mobileThreshold && !this.store.showMobilePlayer && this.store.audioPlayer.audio;
    },
  },
  
};
</script>

<style lang="scss" scope>



#mobile-menu-floaters {
  transition: bottom 200ms ease-in-out;
  position: fixed;
  z-index: 905;
  bottom: 15px;
  right:  15px;
  
  &.mobile {
    bottom: 65px;
  }
  
  @extend .center-contents;
  align-items: flex-end;
  align-content: flex-end;
  flex-direction: column;
  &, a {
    color: #fff !important;
  }
  
  .search-btn {
    transition: top 300ms ease;
    position: absolute;
    top: -93px;
    cursor: pointer;
    @extend .center-contents;
    border-radius: 999999px;
    width:  32px;
    height: 32px;
    // @include themify($themes) {
    //   background: rgba( themed(backColor), .25);
    // }
    &, svg { color: #fff; }
    background: rgba( #292929, .90);
    border: 1px solid rgba( #fff, 1);
  }
  
  .mobile-player-button {
    @extend .search-btn;
    top: -46px;
    background: #ff1946;
    font-size: 1em;
  }
  
  
  .burger-menu {
    cursor: pointer;
    position: relative;
    z-index: 999999999;
    @extend .center-contents;
    width: 60px;
    height: 60px;
    font-size: 1.4em;
    @include themify($themes) {
      background: themed(audibleOrange);
      border: 2px solid rgba( themed(backColor), .8);
    }
    border-radius: 999999px;
    color: #fff;
    box-shadow: 0 2px 15px rgba(#000, .5);
    
  }
  .second-row {
    @extend .center-contents;
  }
  
}

.player-open-indicator {
  display: flex;
  justify-content: center;
  align-items: center;
  position: absolute;
  top: 0;
  right: 0;
  font-size: 11px;
  width: 22px;
  height: 22px;
  border-radius: 999999px;
  @include themify($themes) {
    background: themed(audibleOrange);
    background: #ff1947;
  }
  -webkit-animation:slide-in-blurred-tl .6s cubic-bezier(.23,1.000,.32,1.000) both;animation:slide-in-blurred-tl .6s cubic-bezier(.23,1.000,.32,1.000) both;
  /* ----------------------------------------------
  * Generated by Animista on 2022-7-6 1:16:25
  * Licensed under FreeBSD License.
  * See http://animista.net/license for more info. 
  * w: http://animista.net, t: @cssanimista
  * ---------------------------------------------- */
  @-webkit-keyframes slide-in-blurred-tl{0%{-webkit-transform:translate(-1000px,-1000px) skew(80deg,10deg);transform:translate(-1000px,-1000px) skew(80deg,10deg);-webkit-transform-origin:100% 0;transform-origin:100% 0;-webkit-filter:blur(40px);filter:blur(40px);opacity:0}100%{-webkit-transform:translate(0,0) skew(0deg,0deg);transform:translate(0,0) skew(0deg,0deg);-webkit-transform-origin:50% 50%;transform-origin:50% 50%;-webkit-filter:blur(0);filter:blur(0);opacity:1}}@keyframes slide-in-blurred-tl{0%{-webkit-transform:translate(-1000px,-1000px) skew(80deg,10deg);transform:translate(-1000px,-1000px) skew(80deg,10deg);-webkit-transform-origin:100% 0;transform-origin:100% 0;-webkit-filter:blur(40px);filter:blur(40px);opacity:0}100%{-webkit-transform:translate(0,0) skew(0deg,0deg);transform:translate(0,0) skew(0deg,0deg);-webkit-transform-origin:50% 50%;transform-origin:50% 50%;-webkit-filter:blur(0);filter:blur(0);opacity:1}}
}

</style>