<template>
  <div id="audible-library-extractor">
    <div class="inner-wrap">
      <div class="close-btn" @click="closeOverlay()">
        <humbleicons-times-circle/>
      </div>

      <div id="the-adbl-logo" :class="{ 'fade-in-fwd': showLogo }">
        <img :src="imageSources.logo" alt="" />
      </div>
      <slot></slot>
    </div>
  </div>
</template>

<script>
export default {
  name: "overlay",
  data() {
    return {
      showLogo: false,
      imageSources: {
        logo: chrome.runtime.getURL(
          "assets/images/audible-library-extractor-logo.svg"
        )
      }
    };
  },
  mounted: function() {
    this.showLogo = true;
    document.querySelector("html").classList.add("ale-overlay-open");
  },

  methods: {
    // Instead of destroying the vue instance etc I decided to do
    // the lazy thing and just reload the page... Come at me bro!
    closeOverlay: function() {
      window.location.reload();
    }
  }
};
</script>

<style lang="scss">
html.ale-overlay-open,
html.ale-overlay-open body {
  overflow: hidden !important;
  width: 100% !important;
  height: 100% !important;
}

#audible-library-extractor {
  font-family: "Audible Sans", Arial, sans-serif;
  font-size: 14px;
  line-height: 20px;
  text-decoration: none;
  overflow: auto;

  background: #fff;
  position: fixed;
  z-index: 999999999;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  display: flex;
  justify-content: center;
  justify-items: center;
  align-content: center;
  align-items: center;

  .inner-wrap {
    width: 100%;
    margin: auto;
    text-align: center;
    padding: 60px 0;
  }

  #the-adbl-logo {
    animation-delay: 0.5s !important;
    display: inline-block;
    text-align: center;
    margin-top: 0px;
    margin-bottom: 20px;
    width: 270px;
    height: auto;
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    img {
      display: inline-block;
      width: 100%;
      position: relative;
    }
  }

  .hide {
    display: none;
  }

  .fade-enter-active,
  .fade-leave-active {
    transition: opacity 300ms;
  }

  .fade-enter,
  .fade-leave-to {
    opacity: 0;
  }

  .close-btn {
    display: inline-block;
    padding: 20px;
    color: #b5b5b5;
    font-size: 25px;
    position: fixed;
    top: 0;
    right: 0;
    cursor: pointer;
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    transition: color 500ms ease;
    &:hover {
      color: #222;
    }
  }
}

/* ----------------------------------------------
 * Generated by Animista
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
.fade-in-fwd {
  animation: fade-in-fwd 0.6s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}
@keyframes fade-in-fwd {
  0% {
    transform: translateZ(-80px);
    opacity: 0;
  }
  100% {
    transform: translateZ(0);
    opacity: 1;
  }
}
.puff-in-hor {
  animation: puff-in-hor 0.4s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2ms both;
}
@keyframes puff-in-hor {
  0% {
    transform: scaleX(2);
    filter: blur(4px);
    opacity: 0;
  }
  100% {
    transform: scaleX(1);
    filter: blur(0);
    opacity: 1;
  }
}
.scale-in-hor-center {
  -webkit-animation: scale-in-hor-center 0.5s
    cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: scale-in-hor-center 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}
@-webkit-keyframes scale-in-hor-center {
  0% {
    -webkit-transform: scaleX(0);
    transform: scaleX(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: scaleX(1);
    transform: scaleX(1);
    opacity: 1;
  }
}
@keyframes scale-in-hor-center {
  0% {
    -webkit-transform: scaleX(0);
    transform: scaleX(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: scaleX(1);
    transform: scaleX(1);
    opacity: 1;
  }
}
</style>
