<template>
<div id="audible-library-extractor">
  <div class="center-1">
    <div class="center-2">
      <div class="center-3">
        <div id="the-adbl-logo" :class="{'fade-in-fwd': showLogo }">
          <img :src="imageSources.logo" alt="">
        </div>
        <slot></slot>
      </div>
    </div>
  </div>
</div>
</template>

<script>
export default {
	name: 'aleOverlay',
  data () {
    return {
      showLogo: false,
      imageSources: {
        logo: browser.runtime.getURL("assets/images/audible-library-extractor-logo.svg"),
      }
    }
  },
  mounted: function() {
    
    this.showLogo = true;
    $('html').addClass('ale-overlay-open');
    
  }
}
</script>

<style lang="scss">

.ale-overlay-open body {
	overflow: hidden;
  width: 100%;
  height: 100%;
}

.center-1 {
  display: table;
  height: 100%;
  width: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}

.center-2 {
  display: table-cell;
  vertical-align: middle;
}

.center-3 {
  margin-left: auto;
  margin-right: auto;
  text-align: center;
}

#audible-library-extractor-btn {
  background: #f89a1c;
  button {
    img {
      position: relative;
      top: 3px;
    }
    span {
      color: #fff;
    }
  }
}

#audible-library-extractor [aria-label][data-balloon-pos] {
  &:after {
    line-height: 1.2em;
  }
  &[disabled]:after {
    background: #000 !important;
  }
  &[data-balloon-length="300"]:after {
    white-space: normal;
    width: 300px;
  }
  &[data-balloon-length="350"]:after {
    white-space: normal;
    width: 350px;
  }
  &[data-balloon-length="400"]:after {
    white-space: normal;
    width: 400px;
  }
  &[data-balloon-length="450"]:after {
    white-space: normal;
    width: 450px;
  }
  &[data-balloon-length="500"]:after {
    white-space: normal;
    width: 500px;
  }
  &[data-balloon-length="550"]:after {
    white-space: normal;
    width: 550px;
  }
  &[data-balloon-length="600"]:after {
    white-space: normal;
    width: 600px;
  }
  &[data-balloon-length="650"]:after {
    white-space: normal;
    width: 650px;
  }
  &[data-balloon-length="700"]:after {
    white-space: normal;
    width: 700px;
  }
  &[data-balloon-length="750"]:after {
    white-space: normal;
    width: 750px;
  }
}



#audible-library-extractor {
  font-family: 'Audible Sans', Arial,sans-serif;
  font-size: 14px;
  line-height: 20px;
  text-decoration: none;
	
  background: #fff;
  position: fixed;
  z-index: 999999999;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;

  #the-adbl-logo {
    animation-delay: .5s !important;
    display: inline-block;
    text-align: center;
    margin-bottom: 20px;
    width: 290px;
    height: 99.89px;
    -webkit-touch-callout: none; 
    -webkit-user-select: none; 
    -khtml-user-select: none; 
    -moz-user-select: none; 
    -ms-user-select: none; 
    user-select: none; 
    img {
      display: inline-block;
      width: 100%;
      position: relative;
    }
  }
	
	.hide { display: none; }

  .fade-enter-active,
  .fade-leave-active {
    transition: opacity 300ms;
  }

  .fade-enter,
  .fade-leave-to {
    opacity: 0;
  }
}


/* ----------------------------------------------
 * Generated by Animista
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
.fade-in-fwd{animation:fade-in-fwd .6s cubic-bezier(.39,.575,.565,1.000) both}
@keyframes fade-in-fwd{0%{transform:translateZ(-80px);opacity:0}100%{transform:translateZ(0);opacity:1}}
.puff-in-hor{animation:puff-in-hor .4s cubic-bezier(.47,0.000,.745,.715) .200ms both}
@keyframes puff-in-hor{0%{transform:scaleX(2);filter:blur(4px);opacity:0}100%{transform:scaleX(1);filter:blur(0);opacity:1}}
.scale-in-hor-center{-webkit-animation:scale-in-hor-center .5s cubic-bezier(.25,.46,.45,.94) both;animation:scale-in-hor-center .5s cubic-bezier(.25,.46,.45,.94) both}
@-webkit-keyframes scale-in-hor-center{0%{-webkit-transform:scaleX(0);transform:scaleX(0);opacity:1}100%{-webkit-transform:scaleX(1);transform:scaleX(1);opacity:1}}@keyframes scale-in-hor-center{0%{-webkit-transform:scaleX(0);transform:scaleX(0);opacity:1}100%{-webkit-transform:scaleX(1);transform:scaleX(1);opacity:1}}

</style>
